[package]
name = "receiver"
version = "0.1.0"
authors = ["Marc Newlin <marc.newlin@gmail.com>"]
edition = "2018"

[dependencies]
num = "0.3"
anyhow = "1.0.32"
assert_approx_eq = "1.1.0"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
